import type { Category, Country, Language, Platform } from '@/types';

export const APP_NAME = 'Content Hunter AI Pro';
export const APP_VERSION = typeof __APP_VERSION__ !== 'undefined' ? __APP_VERSION__ : '1.0.0';
export const DEFAULT_API_BASE = 'http://localhost:8787';

export const PLATFORMS: Array<{ id: Platform; label: string }> = [
  { id: 'all', label: 'All Platforms' },
  { id: 'youtube', label: 'YouTube' },
  { id: 'reddit', label: 'Reddit' },
  { id: 'news', label: 'News' },
  { id: 'trends', label: 'Google Trends' },
  { id: 'rss', label: 'RSS Feeds' },
];

export const SORT_OPTIONS = [
  { id: 'relevance', label: 'Relevance' },
  { id: 'engagement', label: 'Engagement' },
  { id: 'growth', label: 'Growth' },
  { id: 'popularity', label: 'Popularity' },
  { id: 'newest', label: 'Newest' },
] as const;

/** ISO 3166-1 alpha-2 countries supported by country filters */
export const COUNTRIES: Country[] = [
  { code: 'US', name: 'United States', region: 'Americas' },
  { code: 'CA', name: 'Canada', region: 'Americas' },
  { code: 'GB', name: 'United Kingdom', region: 'Europe' },
  { code: 'AU', name: 'Australia', region: 'Oceania' },
  { code: 'DE', name: 'Germany', region: 'Europe' },
  { code: 'FR', name: 'France', region: 'Europe' },
  { code: 'JP', name: 'Japan', region: 'Asia' },
  { code: 'PK', name: 'Pakistan', region: 'Asia' },
  { code: 'IN', name: 'India', region: 'Asia' },
  { code: 'BR', name: 'Brazil', region: 'Americas' },
  { code: 'MX', name: 'Mexico', region: 'Americas' },
  { code: 'ES', name: 'Spain', region: 'Europe' },
  { code: 'IT', name: 'Italy', region: 'Europe' },
  { code: 'TR', name: 'Turkey', region: 'Europe' },
  { code: 'MY', name: 'Malaysia', region: 'Asia' },
  { code: 'ID', name: 'Indonesia', region: 'Asia' },
  { code: 'NL', name: 'Netherlands', region: 'Europe' },
  { code: 'SE', name: 'Sweden', region: 'Europe' },
  { code: 'NO', name: 'Norway', region: 'Europe' },
  { code: 'DK', name: 'Denmark', region: 'Europe' },
  { code: 'FI', name: 'Finland', region: 'Europe' },
  { code: 'PL', name: 'Poland', region: 'Europe' },
  { code: 'PT', name: 'Portugal', region: 'Europe' },
  { code: 'IE', name: 'Ireland', region: 'Europe' },
  { code: 'CH', name: 'Switzerland', region: 'Europe' },
  { code: 'AT', name: 'Austria', region: 'Europe' },
  { code: 'BE', name: 'Belgium', region: 'Europe' },
  { code: 'NZ', name: 'New Zealand', region: 'Oceania' },
  { code: 'SG', name: 'Singapore', region: 'Asia' },
  { code: 'KR', name: 'South Korea', region: 'Asia' },
  { code: 'CN', name: 'China', region: 'Asia' },
  { code: 'TW', name: 'Taiwan', region: 'Asia' },
  { code: 'HK', name: 'Hong Kong', region: 'Asia' },
  { code: 'TH', name: 'Thailand', region: 'Asia' },
  { code: 'VN', name: 'Vietnam', region: 'Asia' },
  { code: 'PH', name: 'Philippines', region: 'Asia' },
  { code: 'AE', name: 'United Arab Emirates', region: 'Middle East' },
  { code: 'SA', name: 'Saudi Arabia', region: 'Middle East' },
  { code: 'EG', name: 'Egypt', region: 'Africa' },
  { code: 'ZA', name: 'South Africa', region: 'Africa' },
  { code: 'NG', name: 'Nigeria', region: 'Africa' },
  { code: 'KE', name: 'Kenya', region: 'Africa' },
  { code: 'AR', name: 'Argentina', region: 'Americas' },
  { code: 'CL', name: 'Chile', region: 'Americas' },
  { code: 'CO', name: 'Colombia', region: 'Americas' },
  { code: 'PE', name: 'Peru', region: 'Americas' },
  { code: 'RU', name: 'Russia', region: 'Europe' },
  { code: 'UA', name: 'Ukraine', region: 'Europe' },
  { code: 'IL', name: 'Israel', region: 'Middle East' },
  { code: 'BD', name: 'Bangladesh', region: 'Asia' },
];

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'fr', name: 'French' },
  { code: 'de', name: 'German' },
  { code: 'ar', name: 'Arabic' },
  { code: 'hi', name: 'Hindi' },
  { code: 'ur', name: 'Urdu' },
  { code: 'ja', name: 'Japanese' },
  { code: 'zh', name: 'Chinese' },
  { code: 'ru', name: 'Russian' },
  { code: 'pt', name: 'Portuguese' },
];

export const CATEGORIES: Category[] = [
  { id: 'animals', name: 'Animals', group: 'Lifestyle' },
  { id: 'cats', name: 'Cats', group: 'Lifestyle' },
  { id: 'dogs', name: 'Dogs', group: 'Lifestyle' },
  { id: 'pets', name: 'Pets', group: 'Lifestyle' },
  { id: 'funny', name: 'Funny', group: 'Entertainment' },
  { id: 'gaming', name: 'Gaming', group: 'Gaming' },
  { id: 'minecraft', name: 'Minecraft', group: 'Gaming' },
  { id: 'gta', name: 'GTA', group: 'Gaming' },
  { id: 'roblox', name: 'Roblox', group: 'Gaming' },
  { id: 'fortnite', name: 'Fortnite', group: 'Gaming' },
  { id: 'education', name: 'Education', group: 'Education' },
  { id: 'history', name: 'History', group: 'Education' },
  { id: 'science', name: 'Science', group: 'Education' },
  { id: 'space', name: 'Space', group: 'Education' },
  { id: 'technology', name: 'Technology', group: 'Tech' },
  { id: 'artificial-intelligence', name: 'Artificial Intelligence', group: 'Tech' },
  { id: 'programming', name: 'Programming', group: 'Tech' },
  { id: 'coding', name: 'Coding', group: 'Tech' },
  { id: 'cybersecurity', name: 'Cybersecurity', group: 'Tech' },
  { id: 'finance', name: 'Finance', group: 'Business' },
  { id: 'investing', name: 'Investing', group: 'Business' },
  { id: 'crypto', name: 'Crypto', group: 'Business' },
  { id: 'business', name: 'Business', group: 'Business' },
  { id: 'marketing', name: 'Marketing', group: 'Business' },
  { id: 'sports', name: 'Sports', group: 'Sports' },
  { id: 'football', name: 'Football', group: 'Sports' },
  { id: 'basketball', name: 'Basketball', group: 'Sports' },
  { id: 'cricket', name: 'Cricket', group: 'Sports' },
  { id: 'fitness', name: 'Fitness', group: 'Health' },
  { id: 'gym', name: 'Gym', group: 'Health' },
  { id: 'bodybuilding', name: 'Bodybuilding', group: 'Health' },
  { id: 'yoga', name: 'Yoga', group: 'Health' },
  { id: 'travel', name: 'Travel', group: 'Lifestyle' },
  { id: 'luxury', name: 'Luxury', group: 'Lifestyle' },
  { id: 'cars', name: 'Cars', group: 'Lifestyle' },
  { id: 'motorcycles', name: 'Motorcycles', group: 'Lifestyle' },
  { id: 'food', name: 'Food', group: 'Food' },
  { id: 'cooking', name: 'Cooking', group: 'Food' },
  { id: 'recipes', name: 'Recipes', group: 'Food' },
  { id: 'bbq', name: 'BBQ', group: 'Food' },
  { id: 'desserts', name: 'Desserts', group: 'Food' },
  { id: 'beauty', name: 'Beauty', group: 'Beauty' },
  { id: 'skincare', name: 'Skincare', group: 'Beauty' },
  { id: 'hair-care', name: 'Hair Care', group: 'Beauty' },
  { id: 'makeup', name: 'Makeup', group: 'Beauty' },
  { id: 'fashion', name: 'Fashion', group: 'Lifestyle' },
  { id: 'lifestyle', name: 'Lifestyle', group: 'Lifestyle' },
  { id: 'health', name: 'Health', group: 'Health' },
  { id: 'medical', name: 'Medical', group: 'Health' },
  { id: 'motivation', name: 'Motivation', group: 'Lifestyle' },
  { id: 'quotes', name: 'Quotes', group: 'Lifestyle' },
  { id: 'religion', name: 'Religion', group: 'Lifestyle' },
  { id: 'kids', name: 'Kids', group: 'Family' },
  { id: 'parenting', name: 'Parenting', group: 'Family' },
  { id: 'diy', name: 'DIY', group: 'Home' },
  { id: 'home', name: 'Home', group: 'Home' },
  { id: 'nature', name: 'Nature', group: 'Lifestyle' },
  { id: 'photography', name: 'Photography', group: 'Creative' },
  { id: 'music', name: 'Music', group: 'Entertainment' },
  { id: 'movies', name: 'Movies', group: 'Entertainment' },
  { id: 'celebrities', name: 'Celebrities', group: 'Entertainment' },
  { id: 'memes', name: 'Memes', group: 'Entertainment' },
  { id: 'news', name: 'News', group: 'News' },
  { id: 'politics', name: 'Politics', group: 'News' },
  { id: 'weather', name: 'Weather', group: 'News' },
  { id: 'documentary', name: 'Documentary', group: 'Entertainment' },
  { id: 'shorts', name: 'Shorts', group: 'Formats' },
  { id: 'reels', name: 'Reels', group: 'Formats' },
  { id: 'podcasts', name: 'Podcasts', group: 'Formats' },
  { id: 'asmr', name: 'ASMR', group: 'Formats' },
  { id: 'satisfying', name: 'Satisfying', group: 'Formats' },
  { id: 'luxury-homes', name: 'Luxury Homes', group: 'Home' },
  { id: 'real-estate', name: 'Real Estate', group: 'Business' },
  { id: 'jobs', name: 'Jobs', group: 'Career' },
  { id: 'career', name: 'Career', group: 'Career' },
  { id: 'language-learning', name: 'Language Learning', group: 'Education' },
  { id: 'study', name: 'Study', group: 'Education' },
  { id: 'productivity', name: 'Productivity', group: 'Career' },
  { id: 'books', name: 'Books', group: 'Creative' },
  { id: 'comics', name: 'Comics', group: 'Entertainment' },
  { id: 'anime', name: 'Anime', group: 'Entertainment' },
  { id: 'manga', name: 'Manga', group: 'Entertainment' },
  { id: 'streaming', name: 'Streaming', group: 'Entertainment' },
  { id: 'technology-reviews', name: 'Technology Reviews', group: 'Tech' },
  { id: 'gadgets', name: 'Gadgets', group: 'Tech' },
  { id: 'smartphones', name: 'Smartphones', group: 'Tech' },
  { id: 'laptops', name: 'Laptops', group: 'Tech' },
  { id: 'software', name: 'Software', group: 'Tech' },
  { id: 'open-source', name: 'Open Source', group: 'Tech' },
  { id: 'automation', name: 'Automation', group: 'Tech' },
];

export const AI_FEATURES = [
  { id: 'keyword_expansion', label: 'Keyword Expansion', description: 'Expand a seed keyword into high-value related terms.' },
  { id: 'topic_clustering', label: 'Topic Clustering', description: 'Group related topics into content clusters.' },
  { id: 'trend_analysis', label: 'Trend Analysis', description: 'Explain why a topic is rising or falling.' },
  { id: 'audience_analysis', label: 'Audience Analysis', description: 'Profile the audience behind a topic.' },
  { id: 'seo_score', label: 'SEO Score', description: 'Score SEO potential for a topic or title.' },
  { id: 'content_difficulty', label: 'Content Difficulty', description: 'Estimate how hard it is to rank or go viral.' },
  { id: 'opportunity_score', label: 'Opportunity Score', description: 'Score content opportunity vs competition.' },
  { id: 'related_questions', label: 'Related Questions', description: 'Generate questions your audience is asking.' },
  { id: 'content_calendar', label: 'Content Calendar', description: 'Build a weekly content calendar.' },
  { id: 'headline_generator', label: 'Headline Generator', description: 'Generate scroll-stopping headlines.' },
  { id: 'title_generator', label: 'Title Generator', description: 'Generate platform-ready titles.' },
  { id: 'description_generator', label: 'Description Generator', description: 'Write optimized descriptions.' },
  { id: 'hashtag_generator', label: 'Hashtag Generator', description: 'Suggest relevant hashtags.' },
  { id: 'script_ideas', label: 'Script Ideas', description: 'Outline spoken scripts and talking points.' },
  { id: 'thumbnail_ideas', label: 'Thumbnail Ideas', description: 'Suggest thumbnail concepts and text overlays.' },
  { id: 'hook_generator', label: 'Hook Generator', description: 'Create opening hooks that retain viewers.' },
  { id: 'cta_generator', label: 'Call To Action Generator', description: 'Write compelling CTAs.' },
  { id: 'blog_outline', label: 'Blog Outline Generator', description: 'Structure a blog post outline.' },
  { id: 'youtube_outline', label: 'YouTube Outline Generator', description: 'Structure a YouTube video outline.' },
  { id: 'tiktok_ideas', label: 'TikTok Idea Generator', description: 'Generate short-form video ideas.' },
  { id: 'facebook_post', label: 'Facebook Post Generator', description: 'Draft Facebook posts.' },
  { id: 'instagram_caption', label: 'Instagram Caption Generator', description: 'Write Instagram captions.' },
] as const;

export const NAV_ITEMS = [
  { path: '/', label: 'Dashboard', icon: 'LayoutDashboard' },
  { path: '/search', label: 'Search', icon: 'Search' },
  { path: '/trending', label: 'Trending', icon: 'TrendingUp' },
  { path: '/keywords', label: 'Keyword Explorer', icon: 'KeyRound' },
  { path: '/hashtags', label: 'Hashtag Explorer', icon: 'Hash' },
  { path: '/clusters', label: 'Topic Clusters', icon: 'Network' },
  { path: '/saved', label: 'Saved Ideas', icon: 'Bookmark' },
  { path: '/exports', label: 'Exports', icon: 'Download' },
  { path: '/history', label: 'History', icon: 'History' },
  { path: '/analytics', label: 'Analytics', icon: 'BarChart3' },
  { path: '/ai', label: 'AI Assistant', icon: 'Sparkles' },
  { path: '/settings', label: 'Settings', icon: 'Settings' },
  { path: '/about', label: 'About', icon: 'Info' },
] as const;

export const DEFAULT_SETTINGS = {
  theme: 'system' as const,
  language: 'en',
  defaultCountry: 'US',
  defaultPlatform: 'all' as const,
  autoSave: true,
  notifications: true,
  apiBaseUrl: DEFAULT_API_BASE,
  openaiModel: 'gpt-4o-mini',
  cacheTtlMinutes: 30,
};
